In [17]:
import pandas as pd 
df = pd.read_excel('com_date_list_final.xlsx')
df.rename(columns={'Unnamed: 0':'기업명'},inplace=True)

# df_comname = df['기업명']
# comname_list = df_comname.tolist()

df['등급확정일'] = pd.to_datetime(df['등급확정일'])

In [18]:
df.sort_values('등급확정일')

           기업명       등급결정일      등급확정일
21        플렉스컴  2017.02.07 2017-02-07
105     케이씨씨건설  2017.05.12 2017-05-12
20       쌍용씨앤이  2017.05.31 2017-06-01
84        아주스틸  2017.10.13 2017-10-16
33       대한광통신  2017.10.31 2017-10-31
..         ...         ...        ...
107  현대두산인프라코어  2022.03.31 2022-03-31
82        현대카드  2022.03.31 2022-04-01
30    에스케이이엔에스  2022.04.05 2022-04-06
38   에스케이지오센트릭  2022.04.12 2022-04-13
39        호텔신라  2022.04.14 2022-04-15

[114 rows x 3 columns]

In [2]:
# 파일다운로드 

import requests
import bs4
from bs4 import BeautifulSoup 
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

def get_download(comname):

    url = 'https://www.nicerating.com/disclosure/companyGradeInfo.do?cmpCd=1437314&deviceType=N&isPaidMember=false'
    driver = webdriver.Chrome('C:/Users/82104/Desktop/Untitled Folder/chromedriver')
    driver.implicitly_wait(5)
    driver.get(url)

    검색 = driver.find_element(by=By.XPATH, value='//*[@id="mainSText"]')
    검색.send_keys(comname)

    검색클릭 = driver.find_element(by=By.XPATH, value='//*[@id="searchform"]/fieldset/input')
    검색클릭.click()

    time.sleep(2)
    
    try:
        등급 = driver.find_element(by=By.XPATH, value='//*[@id="tabCompany"]/li[2]/a')
    
    except: 
        pass
    
    else:
        등급 = driver.find_element(by=By.XPATH, value='//*[@id="tabCompany"]/li[2]/a')
        등급.click()
    
        try: 
            driver.find_element(by=By.XPATH, value='//*[@id="tbl4"]/tbody/tr[1]/td[8]/a')
        except:
            pass

        else: 
            time.sleep(5)
            다운로드 = driver.find_element(by=By.XPATH, value='//*[@id="tbl4"]/tbody/tr[1]/td[8]/a')
            다운로드.click()
            time.sleep(5)

            등급확정일 = driver.find_element(by=By.XPATH, value='//*[@id="tbl4"]/tbody/tr[1]/td[5]')
            date = 등급확정일.text


            이름 = driver.find_element(by=By.XPATH, value='//*[@id="dBody"]/section/div[2]/table[1]/tbody/tr/td[1]')
            name = 이름.text
            
            return name, date

In [3]:
# 비금융권 회사들 제무제표 불러오기  

df_list_nonbankname=[]
def get_df_nonbank(filename):

    df = pd.read_excel('com_folder/'+ filename + '.xlsx', header=None)


    #df = df[['회계기준', 'K-IFRS', 'K-IFRS.1', 'K-IFRS.2', 'K-IFRS.3', 'K-IFRS.4', 'K-IFRS.5', 'K-IFRS.6', 'K-IFRS.7']]
    #df.values == '회계기준'
    #df.values
    #df = df[df.values == '유동자산'.index:]
    
    
    try :
        df[df.values == '유동자산'].index[0]
    

    except:
        #print(filename +'은 형식이 다릅니다')
        #com_delete_list.append(filename)
        
        pass
        
    
    else:
        df = df.iloc[:, 2:]
        df = df[df[df.values == '유동자산'].index[0]:]
        #df.drop(columns= [df[df[0:1].isnull()].columns.tolist()])

        value_list = df[1:2].isnull().values.tolist()

        null_list=[]
        for n,i in enumerate(value_list[0]):

            if i == True :

                null_list.append(n)

            else: 
                pass 

        column_list = []
        for n in null_list:    
            column = df.columns[n]
            column_list.append(column)

        df = df.drop(columns=column_list)
        df1 = df.iloc[:, 0]
        df2 = df.iloc[:, -7:-1]
        df= pd.concat([df1, df2], axis=1)
        df.columns = ['회계기준', 'K-IFRS', 'K-IFRS.1', 'K-IFRS.2', 'K-IFRS.3', 'K-IFRS.4', 'K-IFRS.5']
        df.index = range(len(df.index))
        
        print(df)
        df_list_nonbankname.append(filename)
        return df

In [4]:
#금융권 회사들 제무제표 불러오기 

df_list_bankname=[]
def get_df_bank(filename):

    df = pd.read_excel('com_folder/'+ filename + '.xlsx', header=None)


    #df = df[['회계기준', 'K-IFRS', 'K-IFRS.1', 'K-IFRS.2', 'K-IFRS.3', 'K-IFRS.4', 'K-IFRS.5', 'K-IFRS.6', 'K-IFRS.7']]
    #df.values == '회계기준'
    #df.values
    #df = df[df.values == '유동자산'.index:]
    
    
    try :
        df[df.values == '현금및예치금'].index[0]
    

    except:
        #print(filename +'은 형식이 다릅니다')
        #com_delete_list.append(filename)
        
        pass
        
    
    else:
        df = df.iloc[:, 2:]
        df = df[df[df.values == '현금및예치금'].index[0]:]
        #df.drop(columns= [df[df[0:1].isnull()].columns.tolist()])

        value_list = df[1:2].isnull().values.tolist()

        null_list=[]
        for n,i in enumerate(value_list[0]):

            if i == True :

                null_list.append(n)

            else: 
                pass 

        column_list = []
        for n in null_list:    
            column = df.columns[n]
            column_list.append(column)

        df = df.drop(columns=column_list)
        df1 = df.iloc[:, 0]
        df2 = df.iloc[:, -7:-1]
 
        
        df= pd.concat([df1, df2], axis=1)
        df.columns = ['회계기준', 'K-IFRS', 'K-IFRS.1', 'K-IFRS.2', 'K-IFRS.3', 'K-IFRS.4', 'K-IFRS.5']
            
        
        print(filename)
        df_list_bankname.append(filename)
        return df

In [5]:
# 증권, 금융권 기업들 제무제표만 사전형식으로 뽑기 

df_list_bank={}
for c in df['기업명']:

    try:
        get_df_bank(c)
    except:
        pass
    else:
        df_bank = get_df_bank(c)
        df_list_bank[c] = df_bank

하이투자증권
하이투자증권
엔에이치농협캐피탈
엔에이치농협캐피탈
현대차증권
현대차증권
롯데카드
롯데카드

KeyboardInterrupt:

In [338]:
df_list_bankname

['하이투자증권',
 '하이투자증권',
 '엔에이치농협캐피탈',
 '엔에이치농협캐피탈',
 '현대차증권',
 '현대차증권',
 '롯데카드',
 '롯데카드',
 'DB금융투자',
 'DB금융투자',
 '우리금융캐피탈',
 '우리금융캐피탈',
 '유안타증권',
 '유안타증권',
 'BNK투자증권',
 'BNK투자증권',
 '다올투자증권',
 '다올투자증권',
 '현대카드',
 '현대카드',
 '교보증권',
 '교보증권',
 '현대캐피탈',
 '현대캐피탈',
 '한화투자증권',
 '한화투자증권',
 '한국캐피탈',
 '한국캐피탈']

In [339]:
# bankname 

df_list_bankname1 = []
for i in range(len(df_list_bankname)):
    if i%2 == 0:
        df_list_bankname1.append(df_list_bankname[i])

df_list_bankname1

['하이투자증권',
 '엔에이치농협캐피탈',
 '현대차증권',
 '롯데카드',
 'DB금융투자',
 '우리금융캐피탈',
 '유안타증권',
 'BNK투자증권',
 '다올투자증권',
 '현대카드',
 '교보증권',
 '현대캐피탈',
 '한화투자증권',
 '한국캐피탈']

In [6]:
# 최종 bank 기업 dictionary 

df_dic_bank={}
for bn in df_list_bankname1:
    df_dic_bank[bn] = df_list_bank[bn].values

df_dic_bank # 최종 bank 기업 dictionary 
df_dic_bank.keys()

NameError: name 'df_list_bankname1' is not defined

In [325]:
# # 비급융기업들 제무제표만 사전형식으로 뽑기 

# df_list_nonbank={}
# for c in comname_list:
        
#     try:
#         get_df_nonbank(c)
#     except:
#         pass
#     else:
#         df_nonbank = get_df_nonbank(c)
#         df_list_nonbank[c] = df_nonbank

In [7]:
# nonbankname

df_list_nonbankname1 = []
for i in range(len(df_list_nonbankname)):
    if i%2 == 0:
        df_list_nonbankname1.append(df_list_nonbankname[i])

df_list_nonbankname1

[]

In [269]:
# 최종 bank 기업 dictionary 

df_dic_nonbank={}
for nbn in df_list_nonbankname1:
    df_dic_nonbank[nbn] = df_list_nonbank[nbn].values

df_dic_nonbank # 최종 nonbank 기업 dictionary 
df_dic_nonbank.keys()

dict_keys(['두산에너빌리티', '롯데쇼핑', '대우조선해양', '효성티앤씨', '동국제강', '한화토탈에너지스', '롯데렌탈', '에이프로젠제약', '엘엑스하우시스', '에스케이하이닉스', '동국산업', '비보존제약', '한솔케미칼', '강릉에코파워', '한라', '이랜드월드', '한화에너지', '엘지디스플레이', '에스케이이엔에스', '녹십자', '에스케이지오센트릭', '현대로템', '에쓰오일', '에스케이에너지', '에스케이인천석유화학', '호텔신라', '한국항공우주산업', '파라다이스글로벌', '씨제이씨지브이', '케이씨씨', '에코비트', '에스케이브로드밴드', '세아베스틸지주', '풍산', '한화솔루션', '이마트', '삼화페인트공업', '한미약품', '기아', '오씨아이', '한화건설', '이수화학', '부산주공', '엠에스오토텍', '메타랩스', '디엘', '시선인터내셔널', '신원', '해태제과식품', '웅진에너지', '두산', '티케이지태광', '대림', '롯데정밀화학', '금호피앤비화학', '금호석유화학', '에프티이앤이', '롯데글로벌로지스', '현대자동차', '지투하이소닉', '에스케이실트론', 'HSD엔진', '현대트랜시스', '페이퍼코리아', '현대위아', '롯데칠성음료', '트레이스', '한화', '에이치디씨아이파크몰', '한진', '신성이엔지', '에스케이씨', '현대비앤지스틸', '엔씨소프트', '태평양물산', '두산건설', '깨끗한나라', '성창이엔씨', '엘에스엠트론', '한국콜마', '대한항공', '한솔테크닉스', '아시아나항공', '삼성중공업', '동두천드림파워', '대한광통신', '아주스틸', '파루', '대웅제약', '엘에스네트웍스', '포스코건설', '서흥', '한화갤러리아타임월드', '한독', '지에스글로벌', '네이버', '엘지생활건강', '서울제약', '쌍용씨앤이', '에이치디씨', '에스케이루브리컨츠', '롯데케미칼', '포스코인터내셔널', '한국조선해양', '현대삼호중공업', '대우건설', '플렉스컴'])

In [390]:
# 최종기업 list

df_dic_nonbank.keys()
df_dic_bank.keys()

dict1 = df_dic_nonbank.keys() | df_dic_bank.keys()

dict_list = []
for i in dict1:
    dict_list.append(i)


dict_list

['동두천드림파워',
 '풍산',
 '롯데정밀화학',
 '롯데케미칼',
 '현대로템',
 '한화토탈에너지스',
 '파루',
 '한미약품',
 '현대자동차',
 '시선인터내셔널',
 '롯데칠성음료',
 '트레이스',
 '한국콜마',
 '현대캐피탈',
 '금호석유화학',
 '금호피앤비화학',
 '삼화페인트공업',
 '티케이지태광',
 '에스케이루브리컨츠',
 '한화솔루션',
 '디엘',
 '메타랩스',
 '현대비앤지스틸',
 '대한항공',
 '파라다이스글로벌',
 '효성티앤씨',
 '쌍용씨앤이',
 '플렉스컴',
 '하이투자증권',
 '엔에이치농협캐피탈',
 '신성이엔지',
 '태평양물산',
 '지투하이소닉',
 '현대차증권',
 '에스케이브로드밴드',
 '에스케이에너지',
 '네이버',
 '대우조선해양',
 '에스케이이엔에스',
 '한솔케미칼',
 '한독',
 '세아베스틸지주',
 '대한광통신',
 '롯데카드',
 '비보존제약',
 '동국산업',
 '롯데렌탈',
 '신원',
 '서울제약',
 '오씨아이',
 '두산건설',
 '에스케이지오센트릭',
 '호텔신라',
 '한진',
 '성창이엔씨',
 '현대위아',
 '엠에스오토텍',
 '아시아나항공',
 'DB금융투자',
 '에프티이앤이',
 '에스케이씨',
 '대우건설',
 '기아',
 '지에스글로벌',
 'HSD엔진',
 '엘에스네트웍스',
 '대림',
 '씨제이씨지브이',
 '에코비트',
 '녹십자',
 '엔씨소프트',
 '한솔테크닉스',
 '케이씨씨',
 '에스케이실트론',
 '한화건설',
 '한화에너지',
 '해태제과식품',
 '우리금융캐피탈',
 '이수화학',
 '포스코건설',
 '두산',
 '롯데글로벌로지스',
 '유안타증권',
 '부산주공',
 '이랜드월드',
 '에스케이인천석유화학',
 'BNK투자증권',
 '한화투자증권',
 '에이프로젠제약',
 '서흥',
 '삼성중공업',
 '현대삼호중공업',
 '한화갤러리아타임월드',
 '엘지생활건강',
 '에쓰오일',
 '이마트',
 '현대트랜시스',
 '다올투자증권',
 '한국조선해양',
 '엘엑스하우시스',
 '두산에너빌리티',
 '에스케이하이닉스',
 '한화',
 '깨끗한나라',
 '대웅제약',
 '한라',
 '한국캐피탈',
 '강릉에코파워',
 '엘에스엠트론',
 '포스코인터내셔널',
 '현대카드',
 '동국제강',
 '아주스틸',
 '페이퍼코리아',
 '롯데쇼핑',
 '한국항공우주산업',
 '에이치디씨',
 '교보증권',
 '웅진에너지',
 '엘지디스플레이',
 '에이치디씨아이파크몰']

In [8]:
com_date_list = pd.read_excel('com_date_list_final.xlsx')
com_date_list

    Unnamed: 0       등급결정일       등급확정일
0      동두천드림파워  2021.07.12  2021.07.13
1       롯데정밀화학  2019.04.11  2019.04.11
2        롯데케미칼  2021.04.15  2021.04.15
3     한화토탈에너지스  2021.10.20  2021.10.20
4           파루  2020.06.22  2020.06.23
..         ...         ...         ...
109     한화투자증권  2021.12.06  2021.12.06
110     롯데하이마트  2021.06.15  2021.06.15
111      한라홀딩스  2020.06.02  2020.06.03
112      한국캐피탈  2019.06.25  2019.06.25
113     엘에스엠트론  2019.06.25  2019.06.25

[114 rows x 3 columns]

In [9]:
com_date_list = pd.read_excel('com_date_list_final.xlsx')
com_date_list.rename(columns={'Unnamed: 0':'기업명'},inplace=True)
# com_date_list.columns = ['기업명', '등급결정일']
com_date_list['등급결정일']
com_date_list.set_index('기업명')

com_date_list
#for c in com_date_list['기업명']:
#    com_pd[c] = com_date_list['등급결정일']

          기업명       등급결정일       등급확정일
0     동두천드림파워  2021.07.12  2021.07.13
1      롯데정밀화학  2019.04.11  2019.04.11
2       롯데케미칼  2021.04.15  2021.04.15
3    한화토탈에너지스  2021.10.20  2021.10.20
4          파루  2020.06.22  2020.06.23
..        ...         ...         ...
109    한화투자증권  2021.12.06  2021.12.06
110    롯데하이마트  2021.06.15  2021.06.15
111     한라홀딩스  2020.06.02  2020.06.03
112     한국캐피탈  2019.06.25  2019.06.25
113    엘에스엠트론  2019.06.25  2019.06.25

[114 rows x 3 columns]

# 비금융 기업데이터 전처리

In [10]:
#nonbank 기업 하나 불러오기 
import pandas as pd
pd.set_option('display.max_column',None)
df_nonbank = get_df_nonbank('대림')

                                                  회계기준   K-IFRS K-IFRS.1  \
0                                                 유동자산     4096  4271.06
1                                                현금성자산   527.51   408.11
2                                                 매출채권  3092.87  2749.74
3                                                 재고자산   263.17   294.28
4                                                  선급금    22.65    39.89
..                                                 ...      ...      ...
279                    개별재무제표 기준은 별도재무제표 기준을 포괄하는 개념임.      NaN      NaN
280  재무지표상 회계기준 K-GAAP은 K-GAAP자체 또는 K-IFRS가 아닌 회계기준...      NaN      NaN
281  전기 이전 재무제표의 수정은 결산 기준 비교재무제표 또는 수정공시에 한하며, 비상장...      NaN      NaN
282                                                NaN      NaN      NaN
283  ※ 본 재무자료는 회사로부터 제공받거나 공시된 자료에 기초하여 분석을 위한 참조목적...      NaN      NaN

    K-IFRS.2 K-IFRS.3 K-IFRS.4 K-IFRS.5
0    4728.44  4859.32  5292.89  5270.24
1     960.97   939.83   1309.6  1205.39
2    3020.15  3451.94  3456.79  2950.36
3      288.5    182.6    295.1   666.47
4      21.99     24.2    18.17    38.15
..       ...      ...      ...      ...
279      NaN      NaN      NaN      NaN
280      NaN      NaN      NaN      NaN
281      NaN      NaN      NaN      NaN
282      NaN      NaN      NaN      NaN
283      NaN      NaN      NaN      NaN

[284 rows x 7 columns]

In [11]:
df_nonbank.dropna(inplace=True)

In [12]:
# # df_nonbank.drop(['K-IFRS','K-IFRS.1','K-IFRS.2','K-IFRS.3','K-IFRS.4'],axis=1,inplace=True)
# df_nonbank.unstack().unstack()

In [200]:
# df_nonbank.set_index('회계기준')

In [201]:
# #balance sheet _ 비금융데이터

# Bs_begin_idx = df_nonbank[df_nonbank['회계기준'].values == '유동자산'].index[0] 
# Bs_end_idx = df_nonbank[df_nonbank['회계기준'].values == '단기성차입금'].index[0] 

# Bs_nonbank = df_nonbank[Bs_begin_idx:Bs_end_idx+1].set_index('회계기준').dropna()
# Bs_nonbank # balance sheet

In [16]:
a = 3.124154
b = 4.42364546523
print('a={:.3f}, b={:.3f}'.format(a,b))

a=3.124, b=4.424

In [202]:
# Bs_nonbank.reset_index(inplace=True)
# Bs_nonbank.drop(['K-IFRS','K-IFRS.1','K-IFRS.2','K-IFRS.3','K-IFRS.4'],axis=1,inplace=True)
# Bs_nonbank = Bs_nonbank.set_index('회계기준').unstack().unstack()
# Bs_nonbank

In [203]:
# #balance sheet %_ 비금융데이터

# Bs_begin_idx_percentage = df_nonbank[df_nonbank['회계기준'].values == '부채비율(%)'].index[0] 
# Bs_end_idx_percentage = df_nonbank[df_nonbank['회계기준'].values == '운전자금회전기간(일)'].index[0] 

# Bs_percentage_nonbank = df_nonbank[Bs_begin_idx_percentage:Bs_end_idx_percentage+1].set_index('회계기준').dropna()
# Bs_percentage_nonbank # balance sheet (%)

In [204]:
# Bs_percentage_nonbank.reset_index(inplace=True)
# Bs_percentage_nonbank.drop(['K-IFRS','K-IFRS.1','K-IFRS.2','K-IFRS.3','K-IFRS.4'],axis=1,inplace=True)
# Bs_percentage_nonbank = Bs_percentage_nonbank.set_index('회계기준').unstack().unstack()
# Bs_percentage_nonbank

In [205]:
# Bs_join = Bs_nonbank.join(Bs_percentage_nonbank)
# Bs_join

In [206]:
# #income statement _ 비금융데이터


# Is_begin_idx = df_nonbank[df_nonbank['회계기준'].values == '매출액'].index[0] 
# Is_end_idx = df_nonbank[df_nonbank['회계기준'].values == '총포괄이익'].index[0] 

# Is_nonbank = df_nonbank[Is_begin_idx:Is_end_idx+1].set_index('회계기준').dropna()
# Is_nonbank # Income Statement

In [207]:
# Is_nonbank.drop('EBITDA',axis=1,inplace=True)

In [208]:
# Is_nonbank.reset_index(inplace=True)
# Is_nonbank.drop(['K-IFRS','K-IFRS.1','K-IFRS.2','K-IFRS.3','K-IFRS.4'],axis=1,inplace=True)
# Is_nonbank = Is_nonbank.set_index('회계기준').unstack().unstack()
# Is_nonbank

In [209]:
# #income statement % _ 비금융데이터

# Is_begin_idx_percentage = df_nonbank[df_nonbank['회계기준'].values == '매출원가율(%)'].index[0] 
# Is_end_idx_percentage = df_nonbank[df_nonbank['회계기준'].values == 'EBITDA증가율(%)'].index[0] 

# Is_percentage_nonbank = df_nonbank[Is_begin_idx_percentage:Is_end_idx_percentage+1].set_index('회계기준').dropna()
# Is_percentage_nonbank # Income statement (%)

In [210]:
# Is_percentage_nonbank.reset_index(inplace=True)
# Is_percentage_nonbank.drop(['K-IFRS','K-IFRS.1','K-IFRS.2','K-IFRS.3','K-IFRS.4'],axis=1,inplace=True)
# Is_percentage_nonbank = Is_percentage_nonbank.set_index('회계기준').unstack().unstack()
# Is_percentage_nonbank

In [85]:
# Is_join = Is_nonbank.join(Is_percentage_nonbank)

In [211]:
# #Cash Flow  _ 비금융데이터

# CF_begin_idx = df_nonbank[df_nonbank['회계기준'].values == 'EBITDA'].index[1]
# CF_end_idx = df_nonbank[df_nonbank['회계기준'].values == '현금의증가(감소)'].index[0]


# CF_nonbank = df_nonbank[CF_begin_idx:CF_end_idx+1].set_index('회계기준').dropna()
# CF_nonbank #Cash Flow

In [212]:
# CF_nonbank.reset_index(inplace=True)
# CF_nonbank.drop(['K-IFRS','K-IFRS.1','K-IFRS.2','K-IFRS.3','K-IFRS.4'],axis=1,inplace=True)
# CF_nonbank = CF_nonbank.set_index('회계기준').unstack().unstack()
# CF_nonbank

In [213]:
# #Cash Flow % _ 비금융데이터

# CF_begin_idx_percentage = df_nonbank[df_nonbank['회계기준'].values == 'OCF/매출액(%)'].index[0] 
# CF_end_idx_percentage = df_nonbank[df_nonbank['회계기준'].values == '유동성계수(배)'].index[0] 

# CF_percentage_nonbank = df_nonbank[CF_begin_idx_percentage:CF_end_idx_percentage+1].set_index('회계기준').dropna()
# CF_percentage_nonbank # Income statement (%)

In [214]:
# CF_percentage_nonbank.reset_index(inplace=True)
# CF_percentage_nonbank.drop(['K-IFRS','K-IFRS.1','K-IFRS.2','K-IFRS.3','K-IFRS.4'],axis=1,inplace=True)
# CF_percentage_nonbank = CF_percentage_nonbank.set_index('회계기준').unstack().unstack()
# CF_percentage_nonbank

In [215]:
# CF_join = CF_percentage_nonbank.join(CF_nonbank)
# CF_join

# 금융데이터 전처리

In [347]:
#bank 기업 하나 불러오기 
import pandas as pd
import numpy as np
df_bank = get_df_bank('BNK투자증권')
df_bank.index = range(len(df_bank))
df_bank

BNK투자증권

            회계기준 K-IFRS K-IFRS.1 K-IFRS.2 K-IFRS.3 K-IFRS.4 K-IFRS.5
0         현금및예치금    610      667     1603     1071     2410     2354
1           유가증권   9084     6727    14097    20048    21612    28524
2    종속기업및관계기업투자      0        0        0       93      158      866
3           대출채권    521      890     1568     1889     3201     4055
4           기타자산    426      577      710      618     1483      985
..           ...    ...      ...      ...      ...      ...      ...
206          NaN    NaN      NaN      NaN      NaN      NaN      NaN
207          NaN    NaN      NaN      NaN      NaN      NaN      NaN
208          NaN    NaN      NaN      NaN      NaN      NaN      NaN
209          NaN    NaN      NaN      NaN      NaN      NaN      NaN
210          NaN    NaN                        NaN      NaN      NaN

[211 rows x 7 columns]

In [348]:
# K-IFRS.4
df_bank.dropna(inplace=True)
before_bank = df_bank.drop(['K-IFRS','K-IFRS.1','K-IFRS.2','K-IFRS.3','K-IFRS.5'],axis=1)
before_bank.unstack().unstack()

,0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,21,22,23,47,49,50,52,53,54,55,56,58,59,60,69,70,71,72,73,74,75,76,77,78,79,80,82,83,85,86,88,89,90,91,92,93,120,122,124,125,126,127,129,130,131,132
회계기준,현금및예치금,유가증권,종속기업및관계기업투자,대출채권,기타자산,자산총계,예수부채,차입부채,콜머니및차입금,환매조건부채권매도,사채,매도파생결합증권,매도유가증권,기타부채,부채총계,자본금,이익잉여금,자본총계,대고객부채,외부차입부채,우발채무,재무비율,충당금 등/고정이하자산(%),순요주의이하자산비중(%),조정순자본비율 (%)*,순자본비율 (%)*,잉여자본(억원),단순레버리지비율(%),우발채무/자기자본(%),유동성비율(%),조정유동성비율(%),외부차입비중(%),회계기준,재무제표기준,포괄손익계산서 (억원),순수수료손익,수수료수익,수수료비용,순이자손익,이자수익,이자비용,자기매매손익,기타영업손익,순영업손익,판관비,영업이익,영업외순손익,세전계속사업이익,법인세비용,계속사업이익,중단사업손익,당기순이익,기타포괄손익,총포괄이익,재무비율,수수료수익분산도(%),총자산순이익률(ROA)(%),총자본순이익률(ROE)(%),영업이익/순영업수익(%),순영업수익/판관비(%),총자산증가율(%),대고객부채증가율(%),영업이익증가율(%),순이익증가율(%)
K-IFRS.4,2410,21612,158,3201,1483,28864,1760,13353,700,10701,1850,0,102,6771,21885,1330,1249,6979,12564,7540,1382,'20.12,472.6,0.5,519.5,893.8,4178,413.6,19.8,166.4,150.2,26.1,K-IFRS,별도,'20.12,960,1104,144,234,486,251,634,-16,1813,1097,716,4,720,183,537,0,537,24,561,'20.12,61.4,2,9.4,39.5,165.3,21.7,35.6,151.5,157.4

In [349]:
# K-IFRS.5
df_bank.dropna(inplace=True)
df_bank.drop(['K-IFRS','K-IFRS.1','K-IFRS.2','K-IFRS.3','K-IFRS.4'],axis=1,inplace=True)
ex = df_bank.unstack().unstack()

In [350]:
df_before = pd.DataFrame()
df_before['K-IFRS'] = before_bank['K-IFRS.4']
df_before = df_before.unstack().unstack()
df_before.columns = df_bank['회계기준']
df_before.drop(['회계기준','재무제표기준','포괄손익계산서 (억원)','재무비율'],axis=1,inplace=True)
df_before

회계기준,현금및예치금,유가증권,종속기업및관계기업투자,대출채권,기타자산,자산총계,예수부채,차입부채,콜머니및차입금,환매조건부채권매도,사채,매도파생결합증권,매도유가증권,기타부채,부채총계,자본금,이익잉여금,자본총계,대고객부채,외부차입부채,우발채무,충당금 등/고정이하자산(%),순요주의이하자산비중(%),조정순자본비율 (%)*,순자본비율 (%)*,잉여자본(억원),단순레버리지비율(%),우발채무/자기자본(%),유동성비율(%),조정유동성비율(%),외부차입비중(%),순수수료손익,수수료수익,수수료비용,순이자손익,이자수익,이자비용,자기매매손익,기타영업손익,순영업손익,판관비,영업이익,영업외순손익,세전계속사업이익,법인세비용,계속사업이익,중단사업손익,당기순이익,기타포괄손익,총포괄이익,수수료수익분산도(%),총자산순이익률(ROA)(%),총자본순이익률(ROE)(%),영업이익/순영업수익(%),순영업수익/판관비(%),총자산증가율(%),대고객부채증가율(%),영업이익증가율(%),순이익증가율(%)
K-IFRS,2410,21612,158,3201,1483,28864,1760,13353,700,10701,1850,0,102,6771,21885,1330,1249,6979,12564,7540,1382,472.6,0.5,519.5,893.8,4178,413.6,19.8,166.4,150.2,26.1,960,1104,144,234,486,251,634,-16,1813,1097,716,4,720,183,537,0,537,24,561,61.4,2,9.4,39.5,165.3,21.7,35.6,151.5,157.4

In [351]:
df = pd.DataFrame()
df['K-IFRS'] = df_bank['K-IFRS.5']
df = df.unstack().unstack()
df.columns = df_bank['회계기준']
df.drop(['회계기준','재무제표기준','포괄손익계산서 (억원)','재무비율'],axis=1,inplace=True)

In [352]:
df

회계기준,현금및예치금,유가증권,종속기업및관계기업투자,대출채권,기타자산,자산총계,예수부채,차입부채,콜머니및차입금,환매조건부채권매도,사채,매도파생결합증권,매도유가증권,기타부채,부채총계,자본금,이익잉여금,자본총계,대고객부채,외부차입부채,우발채무,충당금 등/고정이하자산(%),순요주의이하자산비중(%),조정순자본비율 (%)*,순자본비율 (%)*,잉여자본(억원),단순레버리지비율(%),우발채무/자기자본(%),유동성비율(%),조정유동성비율(%),외부차입비중(%),순수수료손익,수수료수익,수수료비용,순이자손익,이자수익,이자비용,자기매매손익,기타영업손익,순영업손익,판관비,영업이익,영업외순손익,세전계속사업이익,법인세비용,계속사업이익,중단사업손익,당기순이익,기타포괄손익,총포괄이익,수수료수익분산도(%),총자산순이익률(ROA)(%),총자본순이익률(ROE)(%),영업이익/순영업수익(%),순영업수익/판관비(%),총자산증가율(%),대고객부채증가율(%),영업이익증가율(%),순이익증가율(%)
K-IFRS,2354,28524,866,4055,985,36784,1376,23093,6800,8510,4370,2033,1380,2164,26633,1830,2405,10151,13299,11170,4719,2520.5,0,399,562.8,6572,362.4,46.5,155.3,119.5,30.4,1964,2222,258,425,643,218,874,-25,3239,1862,1377,157,1534,379,1155,0,1155,20,1175,79,3.5,13.5,42.5,173.9,27.4,5.9,92.4,115.2

In [357]:
# balance sheet
df['부채비율'] = df['부채총계'] / df['자본총계'] * 100
df['차입금의존도'] = df['부채총계'] / df['자산총계']
# df['고정장기적합률'] = 
df['자기자본'] = 100 / df['우발채무/자기자본(%)'] * df['우발채무']
df['자기자본순이익률'] = df['당기순이익'] / df['자기자본'] * 100

In [362]:
# income statement
df['총매출액'] = df.iloc[:,35].values + df['자기매매손익'] + df['기타영업손익'] + df.iloc[:,32] + df['기타포괄손익'] + df['영업이익']+df['세전계속사업이익']+df['총포괄이익'] 
df['매출액영업이익률'] = df['영업이익'] / df['총매출액']
df['매출액경상이익률'] = df['당기순이익'] / df['총매출액']
# df['이자보상배율'] = df['EBIT'] / (df['단기차입금'] +  
df['금융비용부담율'] = df['차입부채'] / df['총매출액']
df['순금융비용부담율'] = (df['차입부채'] - df.iloc[:,35].values) / df['총매출액']
df['전년도매출액'] = df_before.iloc[:,35].values + df_before['자기매매손익'] + df_before['기타영업손익'] + df_before.iloc[:,32] + df_before['기타포괄손익'] + df_before['영업이익']+df_before['세전계속사업이익']+df_before['총포괄이익']
df['매출액증가율'] = (df['총매출액'] / df['전년도매출액']) - 1
df['전년도자기자본'] = 100 / df_before['우발채무/자기자본(%)'] * df_before['우발채무']
df['총자산증가율(%)'] = df['총자산증가율(%)']
df['영업이익증가율(%)'] = df['영업이익증가율(%)']
df['자기자본증가율'] = (df['자기자본'] / df['전년도자기자본']) - 1
# df['매출채권회전기일'] = (df['매출채권'] / df['총매출액']) * 365
# df['재고자산회전기일'] = 
# df['매입채무회전기일'] = 
df['총자산회전율'] = df['총매출액'] / df['자산총계']
# df['부채상환계수'] = 
# df['총차입금상환능력비율']
# df['잉여현금흐름/총차입금(%)'] = 
# df['영업현금흐름'] =

In [363]:
df

회계기준,현금및예치금,유가증권,종속기업및관계기업투자,대출채권,기타자산,자산총계,예수부채,차입부채,콜머니및차입금,환매조건부채권매도,사채,매도파생결합증권,매도유가증권,기타부채,부채총계,자본금,이익잉여금,자본총계,대고객부채,외부차입부채,우발채무,충당금 등/고정이하자산(%),순요주의이하자산비중(%),조정순자본비율 (%)*,순자본비율 (%)*,잉여자본(억원),단순레버리지비율(%),우발채무/자기자본(%),유동성비율(%),조정유동성비율(%),외부차입비중(%),순수수료손익,수수료수익,수수료비용,순이자손익,이자수익,이자비용,자기매매손익,기타영업손익,순영업손익,판관비,영업이익,영업외순손익,세전계속사업이익,법인세비용,계속사업이익,중단사업손익,당기순이익,기타포괄손익,총포괄이익,수수료수익분산도(%),총자산순이익률(ROA)(%),총자본순이익률(ROE)(%),영업이익/순영업수익(%),순영업수익/판관비(%),총자산증가율(%),대고객부채증가율(%),영업이익증가율(%),순이익증가율(%),부채비율,차입금의존도,자기자본,자기자본순이익률,총매출액,매출액영업이익률,매출액경상이익률,금융비용부담율,순금융비용부담율,전년도매출액,매출액증가율,전년도자기자본,자기자본증가율,총자산회전율
K-IFRS,2354,28524,866,4055,985,36784,1376,23093,6800,8510,4370,2033,1380,2164,26633,1830,2405,10151,13299,11170,4719,2520.5,0,399,562.8,6572,362.4,46.5,155.3,119.5,30.4,1964,2222,258,425,643,218,874,-25,3239,1862,1377,157,1534,379,1155,0,1155,20,1175,79,3.5,13.5,42.5,173.9,27.4,5.9,92.4,115.2,262.36824,0.724038,10148.387097,11.381119,7820,0.176087,0.147698,2.953069,2.870844,4229,0.849137,6979.79798,0.453966,0.212592

In [226]:
# #balance sheet _ 금융데이터

# Bs_begin_idx = df_bank[df_bank['회계기준'].values == '현금및예치금'].index[0] 
# Bs_end_idx = df_bank[df_bank['회계기준'].values == '자본총계'].index[0] 

# Bs_bank = df_bank[Bs_begin_idx:Bs_end_idx+1].set_index('회계기준').dropna()
# Bs_bank # balance sheet

In [27]:
# balance sheet %_ 금융데이터

Bs_begin_idx_percentage = df_bank[df_bank['회계기준'].values == '충당금 등/고정이하자산(%)'].index[0] 
Bs_end_idx_percentage = df_bank[df_bank['회계기준'].values == '외부차입비중(%)'].index[0] 

Bs_percentage_bank = df_bank[Bs_begin_idx_percentage:Bs_end_idx_percentage+1].set_index('회계기준').dropna()
Bs_percentage_bank # balance sheet (%)

                K-IFRS K-IFRS.1 K-IFRS.2 K-IFRS.3 K-IFRS.4 K-IFRS.5
회계기준
충당금 등/고정이하자산(%)      -    113.5    119.2      356    472.6   2520.5
순요주의이하자산비중(%)        0        0        0        0      0.5        0
조정순자본비율 (%)*     748.8    750.1    863.2    561.4    519.5      399
순자본비율 (%)*       369.2    363.7    699.9    663.1    893.8    562.8
잉여자본(억원)          1719     1693     3258     3085     4178     6572
단순레버리지비율(%)        497    421.5    427.5    536.7    413.6    362.4
우발채무/자기자본(%)      49.3     26.2      9.5       10     19.8     46.5
유동성비율(%)         132.9    143.5    177.5    158.5    166.4    155.3
조정유동성비율(%)       110.5    122.9      168    152.2    150.2    119.5
외부차입비중(%)          8.9     10.2     27.5       38     26.1     30.4

In [28]:
#income statement _ 금융데이터


Is_begin_idx = df_bank[df_bank['회계기준'].values == '순수수료손익'].index[0] 
Is_end_idx = df_bank[df_bank['회계기준'].values == '총포괄이익'].index[0] 

Is_bank = df_bank[Is_begin_idx:Is_end_idx+1].set_index('회계기준').dropna()
Is_bank # Income Statement

         K-IFRS K-IFRS.1 K-IFRS.2 K-IFRS.3 K-IFRS.4 K-IFRS.5
회계기준
순수수료손익      221      244      486      463      960     1964
  수수료수익     315      350      595      573     1104     2222
  수수료비용      94      106      109      110      144      258
순이자손익        78      105      141      132      234      425
  이자수익      157      196      331      466      486      643
  이자비용       79       91      191      334      251      218
자기매매손익      175      104      100      381      634      874
기타영업손익        2      -41        5      -11      -16      -25
순영업손익       476      412      731      966     1813     3239
판관비         352      374      586      681     1097     1862
영업이익        124       38      145      285      716     1377
영업외순손익        1       -9        1        2        4      157
세전계속사업이익    126       30      147      287      720     1534
법인세비용        33       11       33       78      183      379
계속사업이익       93       19      114      209      537     1155
중단사업손익        0        0        0        0        0        0
당기순이익        93       19      114      209      537     1155
기타포괄손익       -4        2       -6        5       24       20
총포괄이익        89       21      107      214      561     1175

In [29]:
#income statement % _ 금융데이터

Is_begin_idx_percentage = df_bank[df_bank['회계기준'].values == '수수료수익분산도(%)'].index[0] 
Is_end_idx_percentage = df_bank[df_bank['회계기준'].values == '순이익증가율(%)'].index[0] 

Is_percentage_bank = df_bank[Is_begin_idx_percentage:Is_end_idx_percentage+1].set_index('회계기준').dropna()
Is_percentage_bank # Income statement (%)

                K-IFRS K-IFRS.1 K-IFRS.2 K-IFRS.3 K-IFRS.4 K-IFRS.5
회계기준
수수료수익분산도(%)       35.8     41.8     65.5     67.4     61.4       79
총자산순이익률(ROA)(%)    1.2      0.2      0.8        1        2      3.5
총자본순이익률(ROE)(%)      5      0.9      3.6      4.8      9.4     13.5
영업이익/순영업수익(%)     26.1      9.3     19.9     29.5     39.5     42.5
순영업수익/판관비(%)     135.3    110.3    124.8    141.8    165.3    173.9
총자산증가율(%)         97.1    -16.7    102.9     31.9     21.7     27.4
대고객부채증가율(%)       79.8      3.8     50.7     16.8     35.6      5.9
영업이익증가율(%)        20.8    -69.2    279.4     95.8    151.5     92.4
순이익증가율(%)         17.6    -79.5    498.1     83.6    157.4    115.2